# Generated by Django 4.1.7 on 2023-04-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_qr_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
