# Generated by Django 4.1.7 on 2023-04-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='image',
            field=models.ImageField(upload_to='qr/'),
        ),
    ]
